[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid

[program:genieacs-cwmp]
command=npm run start-cwmp
directory=/app
autorestart=true
environment=GENIEACS_CWMP_INTERFACE="0.0.0.0"
stdout_logfile=/var/log/cwmp.log
stderr_logfile=/var/log/cwmp.err

[program:genieacs-nbi]
command=npm run start-nbi
directory=/app
autorestart=true
environment=GENIEACS_NBI_INTERFACE="0.0.0.0",GENIEACS_NBI_PORT=7557
stdout_logfile=/var/log/nbi.log
stderr_logfile=/var/log/nbi.err

[program:genieacs-fs]
command=npm run start-fs
directory=/app
autorestart=true
environment=GENIEACS_FS_INTERFACE="0.0.0.0",GENIEACS_FS_PORT=7567
stdout_logfile=/var/log/fs.log
stderr_logfile=/var/log/fs.err

[program:genieacs-ui]
command=npm run start-ui
directory=/app
autorestart=true
environment=GENIEACS_UI_PORT=3000
stdout_logfile=/var/log/ui.log
stderr_logfile=/var/log/ui.err
