[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/log/supervisor/supervisord.pid

[program:mongodb]
command=mongod --dbpath /data/db --bind_ip_all --nojournal --quiet
autorestart=true
stdout_logfile=/var/log/mongodb.log
stderr_logfile=/var/log/mongodb.err
user=root

[program:redis]
command=redis-server --dir /data/redis --loglevel warning --daemonize no
autorestart=true
stdout_logfile=/var/log/redis.log
stderr_logfile=/var/log/redis.err

[program:genieacs-cwmp]
command=npm run start-cwmp
directory=/app
user=node
autorestart=true
environment=GENIEACS_CWMP_INTERFACE="0.0.0.0",GENIEACS_MONGODB_CONNECTION_URL="mongodb://127.0.0.1:27017/genieacs",GENIEACS_REDIS_HOST="127.0.0.1"
stdout_logfile=/var/log/genieacs-cwmp.log
stderr_logfile=/var/log/genieacs-cwmp.err

[program:genieacs-nbi]
command=npm run start-nbi
directory=/app
user=node
autorestart=true
environment=GENIEACS_NBI_INTERFACE="0.0.0.0",GENIEACS_NBI_PORT=7557,GENIEACS_MONGODB_CONNECTION_URL="mongodb://127.0.0.1:27017/genieacs",GENIEACS_REDIS_HOST="127.0.0.1"
stdout_logfile=/var/log/genieacs-nbi.log
stderr_logfile=/var/log/genieacs-nbi.err

[program:genieacs-fs]
command=npm run start-fs
directory=/app
user=node
autorestart=true
environment=GENIEACS_FS_INTERFACE="0.0.0.0",GENIEACS_FS_PORT=7567,GENIEACS_MONGODB_CONNECTION_URL="mongodb://127.0.0.1:27017/genieacs",GENIEACS_REDIS_HOST="127.0.0.1"
stdout_logfile=/var/log/genieacs-fs.log
stderr_logfile=/var/log/genieacs-fs.err

[program:genieacs-ui]
command=npm run start-ui
directory=/app
user=node
autorestart=true
environment=GENIEACS_UI_PORT=3000,GENIEACS_UI_JWT_SECRET="super-secret-change-me-please",GENIEACS_MONGODB_CONNECTION_URL="mongodb://127.0.0.1:27017/genieacs",GENIEACS_REDIS_HOST="127.0.0.1"
stdout_logfile=/var/log/genieacs-ui.log
stderr_logfile=/var/log/genieacs-ui.err
